<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container83PpVxO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container83PpVxO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container83PpVxO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container83PpVxO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container83PpVxO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '83PpVxO',
    'container.build_id' => '06293801',
    'container.build_time' => 1574728294,
], __DIR__.\DIRECTORY_SEPARATOR.'Container83PpVxO');
