<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'get_lists' => [[], ['_controller' => 'App\\Controller\\ListController::getListsAction', '_format' => 'json'], [], [['text', '/api/lists']], [], []],
    'get_list' => [['id'], ['_controller' => 'App\\Controller\\ListController::getListAction', '_format' => 'json'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/lists']], [], []],
    'post_lists' => [[], ['_controller' => 'App\\Controller\\ListController::postListsAction', '_format' => 'json'], [], [['text', '/api/lists']], [], []],
    'get_lists_tasks' => [['id'], ['_controller' => 'App\\Controller\\ListController::getListsTasksAction', '_format' => 'json'], [], [['text', '/tasks'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/lists']], [], []],
    'put_lists' => [[], ['_controller' => 'App\\Controller\\ListController::putListsAction', '_format' => 'json'], [], [['text', '/api/lists']], [], []],
    'patch_lists' => [['id'], ['_controller' => 'App\\Controller\\ListController::patchListsAction', '_format' => 'json'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/lists']], [], []],
];
